typography_spectrum: 0.07173486216925085
color:
  brandColors:
    - '#ffffff'
    - '#727272'
    - '#bc2c36'
    - '#a5a5a5'
    - '#000000'
  brandStrength: 0.5
  lightness: 0.12083119479939342
  saturation: 0.0015353302005678415
  rhythmicContrast: 0.9160773763433099
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.8346155595500022
analytics:
  google: null
  facebook: null
  twitter: null
name: portafolio
cta:
  domain: null
  bucket: null
  version: null
favicon: null
description: Diseño web
purpose: []
