name: portafolio
favicon: null
layout_spectrum: 0.8346155595500022
typography_spectrum: 0.07173486216925085
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.9836550280451775
  lightness: 0.12083119479939342
  saturation: 0.0015353302005678415
  rhythmicContrast: 0.9160773763433099
purpose: []
